### ISSUE TITLE
Better to use video segmentation or image segmentation for sequences? 

### ISSUE THREAD

**Issue by ghost** [karazijal/guess-what-moves#3]
I have a bunch of images generated from a video (to control the frames for downstream tasks, colmap, etc) and they are sequential in time.

**Comment by subhc** [comment]
Video segmentation should ideally be better. The steps would be similar to training on DAVIS. Extract optical flow (RAFT) for the frames and then do internal training. But if the videos have noisy/not object centric optical flow -- for example, due to egomotion, doing optimization on the videos can be detrimental.

**Comment by ghost** [comment]
Thanks for the reply. I am preparing masks for COLMAP. The concern is that with the camera moving (~p/4 radians with ~3 meters radius centered around the object of interest) RAFT has a poor output (not terrible not great). Would you still opt for video in this case?

**Comment by subhc** [comment]
By object centric optical flow I meant optical flow generated due to rigid motion of objects. In this case I am assuming the objects are static and the camera is moving around the object. Then it is the same case as egomotion where the patterns in optical flow are due to disparity change rather than object motion.  I am not sure how well the model perform in such setting. If the forground and background have quadratic affine patterns different enough to emerge a fg-bg separation, training on the video would perform better.

(If the objects are moving then the optical flow is a combination of  parallax due to different disparity values and object's motion. Some kind of pre-processing to remove the optical flow component due to disparity should make the performance better.)
